apiVersion: v1
kind: Service
metadata:
  name: myaapp
spec:
  selector:
    app: myapp  
  ports:
    - port: 80 # port of kubernetes pod
      targetPort: 8080  #container port
      nodePort: 30303  # cluster_port we access aplication on this port 
  type: NodePort